.PHONY: clean All

All:
	@echo "----------Building project:[ C - Debug ]----------"
	@cd "C" && "$(MAKE)" -f  "C.mk"
clean:
	@echo "----------Cleaning project:[ C - Debug ]----------"
	@cd "C" && "$(MAKE)" -f  "C.mk" clean
