.PHONY: clean All

All:
	@echo "----------Building project:[ EJEMPLO8 - Debug ]----------"
	@cd "EJEMPLO8" && "$(MAKE)" -f  "EJEMPLO8.mk"
clean:
	@echo "----------Cleaning project:[ EJEMPLO8 - Debug ]----------"
	@cd "EJEMPLO8" && "$(MAKE)" -f  "EJEMPLO8.mk" clean
